### ISSUE TITLE
Feature: add voltage as prop for battery powered devices.

### ISSUE THREAD

**Issue by jghaanstra** [alexryd/node-shellies#10]
Feature: add voltage as prop for battery powered devices.

**Comment by alexryd** [comment]
Voltage is only available in the HTTP API for some reason. If you need to know the voltage, use the `device.getStatus()` method to retrieve it.

**Comment by jghaanstra** [comment]
Weird, I'll use the REST API for this.

**Comment by jghaanstra** [comment]
I asked on around the Shelly QA Facebook group. Turns out that voltage is available for the Shelly EM and Shelly 3EM. I'm opening this feature request again. It would be nice if this could be added.

```
{"I":4108,"T":"V","D":"voltage","U":"V","R": ["0/265","-1"],"L":2}
```

**Comment by alexryd** [comment]
The Shelly 3EM has three properties for voltage (`voltage0`, `voltage1` and `voltage2`) and the Shelly EM has one property (`voltage0`). You asked about battery powered devices and I assumed you meant H&T, Door/Window etc.

**Comment by jghaanstra** [comment]
Right, I need to get some sleep. Sorry for bother you.

**Comment by alexryd** [comment]
No worries!
