### ISSUE TITLE
powerFactor for Shelly EM

### ISSUE THREAD

**Issue by jghaanstra** [alexryd/node-shellies#12]
The Shelly EM also reports the reactive power. Is this also available under the coap protocol and if so, could this be added to the shellies library?

**Comment by alexryd** [comment]
According to the documentation the Shelly EM doesn't expose powerFactor over CoAP. You can run `shellies description <ip-address>` with the IP address of an EM to get a list of its properties and see if the documentation is correct.

**Comment by jghaanstra** [comment]
I dont own a Shellly EM myself. I'll ask Allterco Robotics if the coap documentation is correct. It's available in the REST API so it seems strange it would not be available in CoAP.

**Comment by jghaanstra** [comment]
According to Allterco Robotics it's not available because there is no room in the CoAP package to add this attribute. I'm closing this for now.
