### ISSUE TITLE
Docker execution

### ISSUE THREAD

**Issue by jmendiara** [alexryd/node-shellies#16]
I'm trying to execute the cli inside a docker container, but unfortunately, no devices are discovered. Native execution directly in the host works perfectly.

I've tried using with and without the host network for the container. I'm using a MAC, so maybe there are limitations on docker networking and the multicast addr

Any clue?

Keep up this good work!

```Dockerfile
FROM node:12.16.1-stretch

RUN npm i -g shellies

ENTRYPOINT ["shellies"]
CMD ["listen"]
```

```sh
docker build -t shellies .

# check is working
docker run --network=host shellies --help
node-shellies 1.1.1

Valid commands: listen, description, status
```

```sh
docker run --network=host shellies listen
# ..... anything found
```

**Comment by alexryd** [comment]
I don't have a lot of experience using Docker, but I did some googling and found this in the docs:

_"The host networking driver only works on Linux hosts, and is not supported on Docker Desktop for Mac, Docker Desktop for Windows, or Docker EE for Windows Server."_

So I suppose it's not supported on a Mac?

**Comment by jmendiara** [comment]
Yeah, sadly i suppose the host operating system it's the limitation here. That issue was just in case there were some issue within the way you are connecting with UDP. 
Thanks for your time!
