### ISSUE TITLE
Supporting new devices

### ISSUE THREAD

**Issue by BobFrankston** [alexryd/node-shellies#3]
First, the package is working very well.

I'm now using the Shellie Duo Bulb and am getting the message
```
payload Changed from [[0,111,1073740964]] to [[0,111,1073741012]]
```
I presume that it's a matter of adding the new device and codes to a table. Where do I find out what the numbers mean? Is there a mechanism for adding new devices without modifying the source code and submitting a new version?

**Comment by alexryd** [comment]
Sorry for the very slow reply. Obviously the Shelly Duo has been added by now. You can find the implementation [here](https://github.com/alexryd/node-shellies/blob/master/lib/devices/shelly-duo.js).

Unfortunately there is no documentation for the CoAP API, but you can get a short description of the properties from the device by running `shellies description <ip-address>`.

**Comment by BobFrankston** [comment]
Thanks. I discovered that npm wasn't updating properly so I uninstalled/reinstalled to get the fix.

**Comment by BobFrankston** [comment]
For clarification, when you say no documentation. Does that mean for your package or for the Shelly CoAP parameters?

**Comment by alexryd** [comment]
For the Shelly CoAP parameters. I just noticed though that they've now added that to the [API documentation](https://shelly-api-docs.shelly.cloud/#coiot-list-of-properties).
