### ISSUE TITLE
addMembership EINVAL

### ISSUE THREAD

**Issue by BobFrankston** [alexryd/node-shellies#6]
Trying to understand this message and how to fix it.

**Comment by alexryd** [comment]
I assume you have found the answer to this question by now.

**Comment by BobFrankston** [comment]
The problem is in the CoAP package which seems to assume only one address per interface and gets an error when there are additional ones. I patch around it for now since my fix is just to put a try / catch around the problematic code and that's not the proper implementation. But the CoAP project itself hasn't responded to the bug report.

Good thing that it is patchable.
